namespace DiskStats.App.Localization;

/// <summary>Die angebotenen Sprachen. Englisch ist die Vorgabe.</summary>
public enum Language { English, German }

/// <summary>
/// Die Texte der Oberflaeche in beiden Sprachen.
///
/// Bewusst eine Tabelle im Quelltext statt Ressourcendateien: Zwei Sprachen passen in eine
/// Datei, und nebeneinander stehende Fassungen lassen sich lesen und vergleichen — bei .resx
/// liegen sie in getrennten Dateien, und dass eine Zeile fehlt, faellt erst zur Laufzeit auf.
/// Hier faellt es beim Lesen auf. Kommen mehr Sprachen dazu, ist der Umstieg ein Umzug der
/// Werte, nicht der Aufrufe.
///
/// Die Sprache wird beim Start gesetzt und danach nicht mehr gewechselt: Ein Teil der Texte
/// steckt in AXAML und wird einmal beim Laden aufgeloest.
/// </summary>
public static class Loc
{
    public static Language Current { get; set; } = Language.English;

    /// <summary>Der Text zum Schluessel. Fehlt er, kommt der Schluessel selbst — sichtbar falsch.</summary>
    public static string T(string key)
        => Table.TryGetValue(key, out (string En, string De) pair)
            ? (Current == Language.German ? pair.De : pair.En)
            : key;

    /// <summary>Wie <see cref="T(string)"/>, mit eingesetzten Werten.</summary>
    public static string T(string key, params object?[] values)
        => string.Format(T(key), values);

    /// <summary>Fuer Tests: beide Fassungen nebeneinander pruefbar.</summary>
    internal static IReadOnlyDictionary<string, (string En, string De)> Entries => Table;

    private static readonly Dictionary<string, (string En, string De)> Table = new()
    {
        ["Preview_Title"] = ("Preview", "Vorschau"),
        ["Preview_Space"] = ("Preview (Space)", "Vorschau (Leertaste)"),
        ["Preview_Loading"] = ("Loading preview…", "Vorschau wird geladen…"),
        ["Preview_Truncated"] = ("Showing the first 128 Ki characters.", "Die ersten 128 Ki Zeichen werden angezeigt."),
        ["Preview_Codecs"] = ("Video support depends on the installed Windows codecs.", "Video-Unterstützung hängt von den installierten Windows-Codecs ab."),
        ["Preview_Play"] = ("Play", "Abspielen"),
        ["Preview_Pause"] = ("Pause", "Pause"),
        ["Preview_Restart"] = ("Restart", "Von vorne"),
        ["Preview_Error"] = ("Preview unavailable: {0}", "Vorschau nicht verfügbar: {0}"),
        ["Preview_Unsupported"] = ("No preview available for this file type.", "Für diesen Dateityp ist keine Vorschau verfügbar."),
        ["Move_Title"] = ("Move to…", "Verschieben nach…"),
        ["Move_Action"] = ("Move", "Verschieben"),
        ["Move_Checking"] = ("Checking files and free space…", "Dateien und freier Speicher werden geprüft…"),
        ["Move_Confirm"] = ("Move {0} entries ({1}) to:\n{2}\n\nFree space: {3}. Windows will ask about name conflicts.", "{0} Einträge ({1}) verschieben nach:\n{2}\n\nFreier Speicher: {3}. Windows fragt bei Namenskonflikten nach."),
        ["Move_Cancelled"] = ("Move cancelled.", "Verschieben abgebrochen."),
        ["Move_Running"] = ("Moving files — progress and cancellation in the Windows dialog.", "Dateien werden verschoben — Fortschritt und Abbruch im Windows-Dialog."),
        ["Move_Done"] = ("Move completed. Scan refreshed.", "Verschieben abgeschlossen. Scan aktualisiert."),
        ["Move_Partial"] = ("Move cancelled. Some files may already have moved; scan refreshed.", "Verschieben abgebrochen. Einige Dateien können bereits verschoben sein; Scan aktualisiert."),
        ["Move_Failed"] = ("Move incomplete (Windows error {0}). Scan refreshed.", "Verschieben unvollständig (Windows-Fehler {0}). Scan aktualisiert."),
        ["Move_Error"] = ("Cannot move files: {0}", "Dateien können nicht verschoben werden: {0}"),
        ["Trend_Title"] = ("History", "Verlauf"),
        ["Trend_Week"] = ("7 days", "7 Tage"),
        ["Trend_Month"] = ("30 days", "30 Tage"),
        ["Trend_Quarter"] = ("90 days", "90 Tage"),
        ["Trend_All"] = ("All retained scans", "Alle gespeicherten Scans"),
        ["Trend_Loading"] = ("Loading scan history…", "Scanverlauf wird geladen…"),
        ["Trend_Retention"] = ("Based on up to 6 retained scans. Actual dates are shown; the baseline may precede the selected period.", "Basis sind bis zu 6 gespeicherte Scans. Die tatsächlichen Daten werden angezeigt; der Ausgangsstand kann vor dem gewählten Zeitraum liegen."),
        ["Trend_Empty"] = ("At least two saved scans are needed for this period. Scan this location again later.", "Für diesen Zeitraum werden mindestens zwei gespeicherte Scans benötigt. Scanne diesen Ort später erneut."),
        ["Trend_Missing"] = ("Not present in this scan", "In diesem Scan nicht vorhanden"),
        ["Trend_Changes"] = ("Changed files and folders", "Veränderte Dateien und Ordner"),
        ["Filter_Saved"] = ("Saved filters", "Gespeicherte Filter"),
        ["Filter_SaveAs"] = ("Filter name", "Filtername"),
        ["Filter_Save"] = ("Save filter", "Filter speichern"),
        ["Filter_Remove"] = ("Remove saved filter", "Gespeicherten Filter entfernen"),
        ["Filter_Replace"] = ("Replace the saved filter “{0}”?", "Gespeicherten Filter „{0}“ ersetzen?"),
        ["Filter_PresetNameError"] = ("Use a name with 1–60 characters.", "Verwende einen Namen mit 1–60 Zeichen."),
        ["Filter_PresetLimit"] = ("Remove a saved filter first (maximum 30).", "Entferne zuerst einen gespeicherten Filter (maximal 30)."),
        ["Health_Title"] = ("Drive health", "Laufwerkszustand"),
        ["Health_Disk"] = ("Physical disk", "Physischer Datenträger"),
        ["Health_FibreChannel"] = ("Fibre Channel", "Fibre Channel"),
        ["Health_Virtual"] = ("Virtual", "Virtuell"),
        ["Health_FileVirtual"] = ("File-backed virtual", "Dateibasierter virtueller Datenträger"),
        ["Health_DiskNumber"] = ("Disk {0}", "Datenträger {0}"),
        ["Health_Device"] = ("Disk {0} · {1} · {2}", "Datenträger {0} · {1} · {2}"),
        ["Health_WindowsStatus"] = ("Health reported by Windows", "Von Windows gemeldeter Zustand"),
        ["Health_Healthy"] = ("Healthy", "In Ordnung"),
        ["Health_Warning"] = ("Warning", "Warnung"),
        ["Health_Unhealthy"] = ("Unhealthy", "Fehlerhaft"),
        ["Health_Unknown"] = ("Unknown", "Unbekannt"),
        ["Health_Temperature"] = ("Temperature", "Temperatur"),
        ["Health_Wear"] = ("Endurance used", "Verbrauchte Lebensdauer"),
        ["Health_Hours"] = ("Power-on hours", "Betriebsstunden"),
        ["Health_ReadErrors"] = ("Read errors (total)", "Lesefehler (gesamt)"),
        ["Health_WriteErrors"] = ("Write errors (total)", "Schreibfehler (gesamt)"),
        ["Health_UncorrectedRead"] = ("Uncorrected read errors", "Nicht korrigierte Lesefehler"),
        ["Health_UncorrectedWrite"] = ("Uncorrected write errors", "Nicht korrigierte Schreibfehler"),
        ["Health_Unavailable"] = ("Not available", "Nicht verfügbar"),
        ["Health_MediaErrors"] = ("NVMe media/data integrity errors", "NVMe-Medien-/Datenintegritätsfehler"),
        ["Health_UnsafeShutdowns"] = ("Unsafe shutdowns", "Unsichere Abschaltungen"),
        ["Health_NvmeClear"] = ("NVMe SMART: no critical warnings", "NVMe SMART: keine kritischen Warnungen"),
        ["Health_NvmeWarning"] = ("NVMe SMART warning: {0} (0x{1})", "NVMe-SMART-Warnung: {0} (0x{1})"),
        ["Health_SpareLow"] = ("spare capacity low", "Reservekapazität niedrig"),
        ["Health_TempWarning"] = ("temperature outside limits", "Temperatur außerhalb der Grenzwerte"),
        ["Health_ReliabilityWarning"] = ("reliability degraded", "Zuverlässigkeit beeinträchtigt"),
        ["Health_ReadOnly"] = ("media is read-only", "Medium ist schreibgeschützt"),
        ["Health_BackupWarning"] = ("volatile memory backup failed", "Sicherung des flüchtigen Speichers ausgefallen"),
        ["Health_PmrWarning"] = ("persistent memory is unreliable", "Persistenter Speicher ist unzuverlässig"),
        ["Health_NvmeReported"] = ("Temperature, endurance and NVMe counters come directly from the SMART log. Other counters use Windows Storage; unsupported values are unavailable.",
                                  "Temperatur, Verschleiß und NVMe-Zähler stammen direkt aus dem SMART-Protokoll. Weitere Zähler liefert Windows Storage; nicht unterstützte Werte sind nicht verfügbar."),
        ["Health_Reported"] = ("Values reported by the Windows Storage provider. Missing or unsupported values are marked as unavailable.",
                               "Vom Windows-Speicheranbieter gemeldete Werte. Fehlende oder nicht unterstützte Werte werden als nicht verfügbar angezeigt."),
        ["Health_Limited"] = ("Windows did not provide the SMART/reliability counters. The driver, USB adapter or current permissions may prevent access; administrator privileges may be required.",
                              "Windows liefert keine SMART-/Zuverlässigkeitszähler. Treiber, USB-Adapter oder aktuelle Berechtigungen können den Zugriff verhindern; möglicherweise sind Administratorrechte nötig."),
        ["Health_Hint"] = ("Read-only query of physical disks. A healthy status is not a guarantee against failure. Wear is the reported percentage used, not a calculated health score.",
                           "Reine Leseabfrage physischer Datenträger. Ein guter Zustand garantiert keinen Schutz vor Ausfällen. Verschleiß ist der gemeldete Verbrauch, kein berechneter Gesundheitsscore."),
        ["Health_Loading"] = ("Reading drive health…", "Laufwerkszustand wird gelesen…"),
        ["Health_Refresh"] = ("Refresh", "Aktualisieren"),
        ["Health_NoDisks"] = ("Windows did not report any physical disks.", "Windows hat keine physischen Datenträger gemeldet."),
        ["Health_Updated"] = ("Updated at {0}", "Aktualisiert um {0}"),
        ["Health_Error"] = ("Could not read drive health: {0}", "Laufwerkszustand konnte nicht gelesen werden: {0}"),
        ["Bench_Title"] = ("Disk speed", "Laufwerkstempo"),
        ["Bench_Drive"] = ("Drive to test", "Laufwerk für den Test"),
        ["Bench_Read"] = ("Read", "Lesen"),
        ["Bench_Write"] = ("Write", "Schreiben"),
        ["Bench_Sequential"] = ("Sequential", "Sequenziell"),
        ["Bench_Random"] = ("Random", "Zufällig"),
        ["Bench_FileSize"] = ("1 GiB test file (1,024 MiB)", "1 GiB Testdatei (1.024 MiB)"),
        ["Bench_Mixed"] = ("Mixed", "Gemischt"),
        ["Bench_MixRatio"] = ("70% read / 30% write", "70 % Lesen / 30 % Schreiben"),
        ["Bench_Combined"] = ("Read + write combined", "Lesen + Schreiben gesamt"),
        ["Bench_Start"] = ("Start test", "Test starten"),
        ["Bench_Free"] = ("{0} free", "{0} frei"),
        ["Bench_Progress"] = ("Test progress", "Testfortschritt"),
        ["Bench_Hint"] = ("Test file removed after the run. Less than 4.2 GiB written. Direct I/O, one request at a time. IOPS = operations/s; ms = average access time.",
                            "Testdatei wird danach entfernt. Unter 4,2 GiB Schreibvolumen. Direktzugriff, eine Anfrage gleichzeitig. IOPS = Zugriffe/s; ms = mittlere Zugriffszeit."),
        ["Bench_Ready"] = ("Close other disk-intensive apps for consistent results.", "Für vergleichbare Werte andere laufwerksintensive Apps schließen."),
        ["Bench_NoDrive"] = ("No ready local drive found. Connect a drive and reopen this window.", "Kein bereites lokales Laufwerk gefunden. Laufwerk anschließen und Fenster erneut öffnen."),
        ["Bench_Preparing"] = ("Preparing the test file…", "Testdatei wird vorbereitet…"),
        ["Bench_SequentialRead"] = ("Sequential read…", "Sequenzielles Lesen…"),
        ["Bench_SequentialWrite"] = ("Sequential write…", "Sequenzielles Schreiben…"),
        ["Bench_RandomRead"] = ("Random 4 KiB read…", "Zufälliges 4-KiB-Lesen…"),
        ["Bench_RandomWrite"] = ("Random 4 KiB write…", "Zufälliges 4-KiB-Schreiben…"),
        ["Bench_Random64Read"] = ("Random 64 KiB read…", "Zufälliges 64-KiB-Lesen…"),
        ["Bench_Random64Write"] = ("Random 64 KiB write…", "Zufälliges 64-KiB-Schreiben…"),
        ["Bench_MixedRandom"] = ("Mixed 4 KiB: 70% read / 30% write…", "Gemischte 4-KiB-Zugriffe: 70 % Lesen / 30 % Schreiben…"),
        ["Bench_Stopping"] = ("Stopping and removing the test file…", "Test wird beendet und Testdatei entfernt…"),
        ["Bench_Cancelled"] = ("Cancelled. Test file removed; completed results remain visible.", "Abgebrochen. Testdatei entfernt; fertige Messwerte bleiben sichtbar."),
        ["Bench_Complete"] = ("Complete. Test file removed.", "Fertig. Testdatei entfernt."),
        ["Bench_Error"] = ("Test could not finish: {0}", "Test konnte nicht beendet werden: {0}"),
        ["Bench_Busy"] = ("Finish the current scan or file operation before testing disk speed.", "Vor dem Tempotest den laufenden Scan oder Dateivorgang beenden."),
        // ---------- Allgemein ----------
        ["Common_Cancel"] = ("Cancel", "Abbrechen"),
        ["Common_Close"] = ("Close", "Schließen"),
        ["Common_Done"] = ("Done", "Fertig"),
        ["Common_Ready"] = ("Ready", "Bereit"),
        ["Common_Empty"] = ("—", "—"),

        // ---------- Seitenleiste ----------
        ["Side_Drives"] = ("DRIVES", "LAUFWERKE"),
        ["Side_QuickWins"] = ("QUICK WINS", "QUICK WINS"),
        ["Side_FileTypes"] = ("FILE TYPES", "DATEITYPEN"),
        ["Side_Duplicates"] = ("DUPLICATES", "DUPLIKATE"),
        ["Side_Changes"] = ("CHANGES", "VERÄNDERT"),
        ["Side_Browse"] = ("Browse", "Durchsuchen"),
        ["Side_BrowseTip"] = ("Choose a folder or drive", "Ordner oder Laufwerk wählen"),
        ["Side_ThemeTip"] = ("Light or dark theme", "Helles oder dunkles Thema"),
        ["Side_ToDark"] = ("Switch to the dark theme", "Zum dunklen Thema wechseln"),
        ["Side_ToLight"] = ("Switch to the light theme", "Zum hellen Thema wechseln"),
        ["Side_FreeOf"] = ("{0} free", "{0} frei"),

        // ---------- Kopfbereich ----------
        ["Head_NothingScanned"] = ("Nothing scanned yet", "Noch nichts gescannt"),
        ["Head_Search"] = ("Search …  (Ctrl+F)", "Suchen …  (Strg+F)"),
        ["Head_UpTip"] = ("One level up", "Eine Ebene zurück"),
        ["Head_Counts"] = ("{0}   ·   {1} files   ·   {2} folders",
                           "{0}   ·   {1} Dateien   ·   {2} Ordner"),
        ["Head_StartHint"] = ("Pick a drive on the left to begin",
                              "Wähle links ein Laufwerk, um zu starten"),

        // ---------- Ansichten ----------
        ["View_Treemap"] = ("Treemap", "Treemap"),
        ["View_TreemapHint"] = ("Area by bytes", "Fläche nach Bytes"),
        ["View_Folders"] = ("Folders", "Ordner"),
        ["View_FoldersHint"] = ("One level, by size", "Eine Ebene, nach Größe"),
        ["View_Files"] = ("Files", "Dateien"),
        ["View_FilesHint"] = ("Sortable file table with subfolders", "Sortierbare Dateitabelle mit Unterordnern"),
        ["View_Sunburst"] = ("Sunburst", "Sunburst"),
        ["View_SunburstHint"] = ("Rings by size", "Ringe nach Größe"),
        ["View_Flame"] = ("Flame", "Flame"),
        ["View_FlameHint"] = ("Depth downwards", "Tiefe nach unten"),
        ["View_Bubbles"] = ("Bubbles", "Bubbles"),
        ["View_BubblesHint"] = ("Circles by size", "Kreise nach Größe"),
        ["View_MindMap"] = ("Mind Map", "Mind Map"),
        ["View_MindMapHint"] = ("The 10 largest folders", "Die 10 größten Ordner"),
        ["View_TopSizes"] = ("Top Sizes", "Top Sizes"),
        ["View_TopSizesHint"] = ("The largest files", "Die größten Dateien"),
        ["View_AgeMap"] = ("Age Map", "Age Map"),
        ["View_AgeMapHint"] = ("Big and long untouched", "Groß und lange unberührt"),
        ["View_Empty"] = ("This folder is empty", "Dieser Ordner ist leer"),
        ["View_NoFolders"] = ("No subfolders here", "Hier gibt es keine Unterordner"),
        ["View_MoreFolders"] = ("{0} more folders  ·  {1} together",
                                "{0} weitere Ordner  ·  zusammen {1}"),
        ["View_NoFiles"] = ("No files in this range", "Keine Dateien in diesem Bereich"),
        ["View_AgeAxis"] = ("BYTES BY YEAR OF CHANGE", "BYTES NACH ÄNDERUNGSJAHR"),
        ["View_NothingStale"] = ("Nothing large here has sat untouched for over a year",
                                 "Nichts Großes liegt hier länger als ein Jahr unberührt"),
        ["View_StaleTotal"] = ("Large and untouched for over a year  ·  {0} in total",
                               "Groß und seit über einem Jahr unberührt  ·  {0} insgesamt"),

        // ---------- Einfaerbung ----------
        ["Color_Label"] = ("Colour", "Fläche"),
        ["Color_ByFolder"] = ("Folder", "Ordner"),
        ["Color_ByType"] = ("Type", "Typ"),
        ["Color_ByAge"] = ("Age", "Alter"),
        ["Color_Fresh"] = ("fresh", "frisch"),
        ["Color_Old"] = ("5 years and older", "5 Jahre und älter"),

        // ---------- Dateitypen ----------
        ["Types_ByExtension"] = ("Extension", "Endung"),
        ["Types_ByKind"] = ("Kind", "Art"),
        ["Types_NoExtension"] = ("(none)", "(ohne)"),
        ["Types_Highlighted"] = ("{0} highlighted — click again to clear",
                                 "{0} hervorgehoben — nochmal klicken hebt es auf"),

        // ---------- Kategorien ----------
        ["Cat_Video"] = ("Video", "Video"),
        ["Cat_Audio"] = ("Audio", "Audio"),
        ["Cat_Images"] = ("Images", "Bilder"),
        ["Cat_Documents"] = ("Documents", "Dokumente"),
        ["Cat_Archives"] = ("Archives", "Archive"),
        ["Cat_Code"] = ("Code", "Code"),
        ["Cat_Programs"] = ("Programs", "Programme"),
        ["Cat_Other"] = ("Other", "Sonstiges"),

        // ---------- Datentraeger ----------
        ["Disk_Nvme"] = ("NVMe", "NVMe"),
        ["Disk_Ssd"] = ("SSD", "SSD"),
        ["Disk_Hdd"] = ("Hard disk", "Festplatte"),
        ["Disk_Removable"] = ("Removable drive", "Wechseldatenträger"),
        ["Disk_Network"] = ("Network drive", "Netzlaufwerk"),
        ["Disk_Optical"] = ("Optical drive", "Optisches Laufwerk"),
        ["Disk_Ram"] = ("RAM disk", "RAM-Datenträger"),
        ["Disk_Cloud"] = ("Cloud drive", "Cloud-Laufwerk"),
        ["Disk_Unknown"] = ("Volume", "Datenträger"),

        // ---------- Inspektor ----------
        ["Insp_Selection"] = ("SELECTION", "AUSWAHL"),
        ["Insp_Folder"] = ("FOLDER", "ORDNER"),
        ["Insp_File"] = ("FILE", "DATEI"),
        ["Insp_Nothing"] = ("Nothing selected", "Nichts ausgewählt"),
        ["Insp_Details"] = ("DETAILS", "DETAILS"),
        ["Insp_Largest"] = ("LARGEST CONTENTS", "GRÖSSTE INHALTE"),
        ["Insp_NoChildren"] = ("No contents", "Keine Unterelemente"),
        ["Insp_Entries"] = ("{0} entries", "{0} Einträge"),
        ["Insp_DirectEntries"] = ("Direct entries", "Direkte Einträge"),
        ["Insp_Category"] = ("Category", "Kategorie"),
        ["Insp_Modified"] = ("Modified", "Geändert"),
        ["Insp_ShareOfFolder"] = ("Share of folder", "Anteil am Ordner"),
        ["Insp_ShareOfDrive"] = ("Share of {0}", "Anteil an {0}"),
        ["Insp_ShareOfScan"] = ("{0} of the scan", "{0} des Scans"),
        ["Insp_Reveal"] = ("Show in Explorer", "Im Explorer"),
        ["Insp_CopyPath"] = ("Copy path", "Pfad kopieren"),
        ["Insp_SettingsTip"] = ("Settings", "Einstellungen"),

        // ---------- Kontextmenue ----------
        ["Menu_Open"] = ("Go into", "Hineingehen"),
        ["Menu_Reveal"] = ("Show in Explorer", "Im Explorer zeigen"),
        ["Menu_CopyPath"] = ("Copy path", "Pfad kopieren"),
        ["Menu_Export"] = ("Export as CSV", "Als CSV exportieren"),
        ["Menu_Stage"] = ("Add to clean-up list", "Zum Aufräumen vormerken"),

        // ---------- Aufraeumen ----------
        ["Table_Title"] = ("File table", "Dateitabelle"),
        ["Table_Name"] = ("Name", "Name"),
        ["Table_Logical"] = ("File size", "Dateigröße"),
        ["Table_Physical"] = ("On disk", "Belegt"),
        ["Table_Modified"] = ("Modified", "Geändert"),
        ["Table_Files"] = ("Files", "Dateien"),
        ["Table_Links"] = ("Links", "Links"),
        ["Table_Path"] = ("Path", "Pfad"),
        ["Table_Recursive"] = ("Include subfolders", "Unterordner einbeziehen"),
        ["Table_Loading"] = ("Loading…", "Wird geladen…"),
        ["Table_Count"] = ("{0:N0} entries", "{0:N0} Einträge"),
        ["Table_Capped"] = ("Showing {0:N0} of {1:N0} entries — narrow down with filters",
            "{0:N0} von {1:N0} Einträgen gezeigt — mit Filtern eingrenzen"),
        ["Storage_Unknown"] = ("Allocation unknown", "Belegung unbekannt"),
        ["Storage_Allocated"] = ("{0} on disk", "{0} auf Datenträger belegt"),
        ["Storage_Missing"] = ("+ {0:N0} unknown; hardlinks counted once", "+ {0:N0} unbekannt; Hardlinks einmal gezählt"),
        ["Storage_Links"] = ("{0} hardlinks share this storage.", "{0} Hardlinks teilen diesen Speicher."),
        ["Filter_Title"] = ("Filters", "Filter"),
        ["Filter_Name"] = ("Name pattern", "Namensmuster"),
        ["Filter_Path"] = ("Relative path pattern", "Muster für relativen Pfad"),
        ["Filter_Regex"] = ("Use regular expressions", "Reguläre Ausdrücke verwenden"),
        ["Filter_Min"] = ("Minimum file size (bytes)", "Minimale Dateigröße (Bytes)"),
        ["Filter_Max"] = ("Maximum file size (bytes)", "Maximale Dateigröße (Bytes)"),
        ["Filter_Age"] = ("Not modified for at least this many days", "Seit mindestens so vielen Tagen unverändert"),
        ["Filter_Exclude"] = ("Exclude from scans: one path or glob per line", "Vom Scan ausschließen: ein Pfad oder Glob pro Zeile"),
        ["Filter_Hint"] = ("Empty fields impose no restriction. Globs: *.log, archive/**. Exclusions trigger a new scan; result filters apply to the table.",
                           "Leere Felder schränken nicht ein. Globs: *.log, archive/**. Ausschlüsse starten einen neuen Scan; Ergebnisfilter gelten für die Tabelle."),
        ["Filter_Invalid"] = ("Please check the filter: {0}", "Bitte Filter prüfen: {0}"),
        ["Filter_Reset"] = ("Clear result filters", "Ergebnisfilter leeren"),
        ["Filter_Apply"] = ("Apply", "Anwenden"),
        ["Refresh_Folder"] = ("Refresh folder", "Ordner aktualisieren"),
        ["Watch_Title"] = ("Watch changes", "Änderungen überwachen"),
        ["Watch_Overflow"] = ("Change buffer overflow; checking the scan again.", "Änderungspuffer übergelaufen; Scan wird erneut geprüft."),
        ["Watch_Failed"] = ("Cannot watch this folder: {0}", "Ordner kann nicht überwacht werden: {0}"),
        ["Refresh_Running"] = ("Refreshing {0}…", "{0} wird aktualisiert…"),
        ["Refresh_Done"] = ("Refreshed: {0}", "Aktualisiert: {0}"),
        ["Refresh_Failed"] = ("Refresh failed: {0}", "Aktualisierung fehlgeschlagen: {0}"),
        ["Filter_ExcludeSelected"] = ("Exclude from scans", "Vom Scan ausschließen"),
        ["Scan_Auto"] = ("Automatic", "Automatisch"),
        ["Scan_Directory"] = ("Directory scan", "Verzeichnisscan"),
        ["Scan_Ntfs"] = ("NTFS / MFT", "NTFS / MFT"),
        ["Scan_MethodHint"] = ("Automatic uses direct NTFS reads for whole volumes. This needs administrator rights. Unsupported volumes or denied access fall back to directory scanning.",
                              "Automatisch nutzt direkte NTFS-Zugriffe bei ganzen Laufwerken. Dafür sind Administratorrechte nötig. Bei anderen Laufwerken oder verweigertem Zugriff wird normal gescannt."),
        ["Scan_NtfsUsed"] = ("Direct NTFS scan.", "Direkter NTFS-Scan."),
        ["Scan_DirectoryUsed"] = ("Directory scan.", "Verzeichnisscan."),
        ["Scan_Fallback"] = ("NTFS unavailable: {0}", "NTFS nicht verfügbar: {0}"),
        ["Clean_Title"] = ("CLEAN UP", "AUFRÄUMEN"),
        ["Clean_Stage"] = ("Add to clean-up list", "Zum Aufräumen vormerken"),
        ["Clean_Clear"] = ("Clear", "Leeren"),
        ["Clean_Move"] = ("Move", "Verschieben"),
        ["Clean_Delete"] = ("Move to Recycle Bin", "In den Papierkorb"),
        ["Clean_Summary"] = ("{0} entries, {1} in total ", "{0} Einträge mit zusammen {1} "),
        ["Clean_SummaryOne"] = ("one entry, {1} ", "einen Eintrag mit {1} "),
        ["Clean_Staged"] = ("Added: {0}", "Vorgemerkt: {0}"),
        ["Clean_NotPossible"] = ("Not possible: {0}", "Nicht möglich: {0}"),
        ["Clean_Confirm"] = ("Move {0} to the Recycle Bin?", "{0} in den Papierkorb verschieben?"),
        ["Clean_Moved"] = ("{0} entries ({1}) moved to the Recycle Bin",
                           "{0} Einträge ({1}) in den Papierkorb verschoben"),
        ["Clean_Partial"] = ("Not everything moved ({0}) — remaining entries checked again",
                             "Nicht alles verschoben ({0}) — verbliebene Einträge erneut geprüft"),
        ["Clean_Checking"] = ("Checking remaining files after clean-up…",
                              "Verbliebene Dateien nach dem Aufräumen werden geprüft…"),
        ["Clean_Remaining"] = ("Some paths still exist", "Einige Pfade sind noch vorhanden"),
        ["Clean_RefreshFailed"] = ("Could not refresh after clean-up: {0}. Please scan again.",
                                  "Abgleich nach dem Aufräumen fehlgeschlagen: {0}. Bitte erneut scannen."),
        ["Clean_BinError"] = ("Recycle Bin: {0} on {1} entries",
                              "Papierkorb: {0} bei {1} Einträgen"),
        ["Clean_ErrorCode"] = ("Error code {0}", "Fehlercode {0}"),

        // ---------- Ablehnungen ----------
        ["Deny_NoPath"] = ("No path", "Kein Pfad"),
        ["Deny_InvalidPath"] = ("Invalid path", "Ungültiger Pfad"),
        ["Deny_NoDrive"] = ("No drive recognised", "Kein Laufwerk erkennbar"),
        ["Deny_WholeDrive"] = ("The entire drive", "Das ganze Laufwerk"),
        ["Deny_WholeProfile"] = ("The entire user profile", "Das ganze Benutzerprofil"),
        ["Deny_SystemFolder"] = ("System folder {0}", "Systemordner {0}"),
        ["Deny_SystemFile"] = ("System file {0}", "Systemdatei {0}"),
        ["Deny_Removed"] = ("Already removed", "Bereits entfernt"),
        ["Deny_ScanRoot"] = ("The root of the scan", "Die Wurzel des Scans"),
        ["Deny_AlreadyListed"] = ("Already on the list", "Steht schon auf der Liste"),
        ["Deny_InsideListed"] = ("Already inside {0}", "Liegt bereits in {0}"),

        // ---------- Quick Wins ----------
        ["Win_Total"] = ("QUICK WINS", "QUICK WINS"),
        ["Win_Regrows"] = ("{0} places · grows back", "{0} Stellen · wächst nach"),
        ["Win_LookFirst"] = ("{0} places · look first", "{0} Stellen · erst ansehen"),
        ["Win_Staged"] = ("{0} places added — check below, then to the Recycle Bin",
                          "{0} Stellen vorgemerkt — unten prüfen, dann in den Papierkorb"),
        ["Win_StagedSome"] = ("{0} of {1} added, the rest is protected or already listed",
                              "{0} von {1} vorgemerkt, der Rest ist gesperrt oder schon gelistet"),
        ["Win_GroupHead"] = ("{0} — {1}", "{0} — {1}"),

        ["Win_PackageDirs"] = ("Package directories", "Paket-Verzeichnisse"),
        ["Win_PackageDirsHint"] = ("Possible package directories; check for local changes before removing",
                                   "Mögliche Paket-Verzeichnisse; vor dem Entfernen auf eigene Änderungen prüfen"),
        ["Win_PackageCaches"] = ("Fetched packages", "Geladene Pakete"),
        ["Win_PackageCachesHint"] = ("May also contain configuration, credentials and installed tools",
                                   "Kann auch Konfiguration, Zugangsdaten und installierte Werkzeuge enthalten"),
        ["Win_BuildOutput"] = ("Build output", "Build-Ergebnisse"),
        ["Win_BuildOutputHint"] = ("Next to a project file — the next build recreates it",
                                   "Neben einer Projektdatei — der nächste Build erzeugt es neu"),
        ["Win_VirtualEnvs"] = ("Virtual environments", "Virtuelle Umgebungen"),
        ["Win_VirtualEnvsHint"] = ("Check dependencies, configuration and local changes before removing",
                                   "Vor dem Entfernen Abhängigkeiten, Konfiguration und eigene Änderungen prüfen"),
        ["Win_PyCaches"] = ("Python caches", "Python-Zwischenspeicher"),
        ["Win_PyCachesHint"] = ("Compiled bytecode and test caches — recreated on the next run",
                                "Kompilierter Bytecode und Test-Caches — entstehen beim nächsten Lauf neu"),
        ["Win_AppCaches"] = ("Caches", "Zwischenspeicher"),
        ["Win_AppCachesHint"] = ("Possible cache; may contain offline data or application state",
                                   "Möglicher Cache; kann Offline-Daten oder Anwendungszustand enthalten"),
        ["Win_TempFiles"] = ("Temporary files", "Temporäre Dateien"),
        ["Win_TempFilesHint"] = ("Check contents; files may still be needed by running programs",
                                   "Inhalt prüfen; laufende Programme können Dateien noch benötigen"),
        ["Win_WindowsOld"] = ("Previous Windows version", "Alte Windows-Version"),
        ["Win_WindowsOldHint"] = ("Left behind by a major update — deleting it ends the way back",
                                  "Bleibt nach einem großen Update liegen — danach ist kein Zurück mehr möglich"),
        ["Win_Downloads"] = ("Downloads", "Downloads"),
        ["Win_DownloadsHint"] = ("Holds your own files — look through it yourself",
                                 "Enthält eigene Dateien — bitte selbst durchsehen"),
        ["Win_VmImages"] = ("VM images", "VM-Abbilder"),
        ["Win_VmImagesHint"] = ("WSL and Docker. Deleting destroys the system inside",
                                "WSL und Docker. Löschen vernichtet das enthaltene System"),

        // ---------- Zwischenstaende ----------
        ["Cache_Title"] = ("STORED DATA", "GESPEICHERTE DATEN"),
        ["Cache_Hint"] = (
            "Snapshots let a folder come back in a second instead of minutes. {0} in use.",
            "Snapshots holen einen Ordner in einer Sekunde zurück statt in Minuten. "
            + "Belegt: {0}."),
        ["Cache_Clear"] = ("Delete", "Löschen"),
        ["Cache_Cleared"] = ("{0} freed", "{0} frei geworden"),
        ["Cache_Empty"] = ("Nothing stored", "Nichts gespeichert"),

        // ---------- Erhoehte Rechte ----------
        ["Elev_Title"] = ("Run as administrator?", "Mit Administratorrechten starten?"),
        ["Elev_Question"] = (
            "Some folders are closed to your account — the status bar names how many. As "
            + "administrator DiskStats gets into many of them, though not all, and the totals "
            + "come closer to the truth. Nothing else changes.",
            "Einige Ordner sind für dein Konto gesperrt — die Statuszeile nennt, wie viele. "
            + "Als Administrator kommt DiskStats in viele davon hinein, wenn auch nicht in "
            + "alle, und die Summen rücken näher an die Wahrheit. Sonst ändert sich nichts."),
        ["Elev_Yes"] = ("Restart as administrator", "Als Administrator neu starten"),
        ["Elev_Remember"] = ("Don't ask again", "Nicht mehr fragen"),
        ["Elev_Setting"] = ("Ask about administrator rights at startup",
                            "Beim Start nach Administratorrechten fragen"),
        ["Elev_SettingHint"] = (
            "Only offered when your account can elevate at all.",
            "Wird nur angeboten, wenn dein Konto überhaupt erhöhen kann."),
        ["Elev_Running"] = ("Running as administrator", "Läuft als Administrator"),

        // ---------- Namen fuer Vorlesewerkzeuge ----------
        ["A11y_Map"] = ("Map of the scanned folder", "Karte des gescannten Ordners"),
        ["A11y_MapEmpty"] = ("Map, nothing scanned yet", "Karte, noch nichts gescannt"),
        ["A11y_Selected"] = ("{0}, {1}, {2} of {3}", "{0}, {1}, {2} von {3}"),
        ["A11y_Search"] = ("Search in the scanned folder", "Im gescannten Ordner suchen"),
        ["A11y_Unstage"] = ("Remove from the clean-up list", "Von der Aufräumliste nehmen"),
        ["A11y_Drive"] = ("Scanned volume: {0}", "Gescannter Datenträger: {0}"),
        ["A11y_Rescan"] = ("Scan again (F5)", "Erneut scannen (F5)"),

        // ---------- Veraenderungen ----------
        ["Chg_Since"] = ("since {0}", "seit {0}"),
        ["Chg_Nothing"] = ("Nothing notable has changed",
                           "Nichts Nennenswertes hat sich geändert"),
        ["Chg_Added"] = ("new", "neu"),
        ["Chg_Removed"] = ("gone", "weg"),

        // ---------- Duplikate ----------
        ["Dup_Search"] = ("Search for duplicates", "Nach Duplikaten suchen"),
        ["Dup_Hint"] = ("Reads file contents — takes a moment",
                        "Liest die Dateien — dauert einen Moment"),
        ["Dup_Running"] = ("Comparing {0} of {1} …", "Vergleicht {0} von {1} …"),
        ["Dup_None"] = ("No duplicates over {0}", "Keine Duplikate über {0}"),
        ["Dup_Copies"] = ("{0} copies · {1} each", "{0} Fassungen · je {1}"),
        ["Dup_GroupHead"] = ("{0} IDENTICAL FILES, {1} EACH — KEEP ONE",
                             "{0} GLEICHE DATEIEN, JE {1} — EINE BEHALTEN"),
        ["Dup_Cancelled"] = ("Duplicate search cancelled", "Duplikatsuche abgebrochen"),
        ["Dup_Failed"] = ("Duplicate search failed: {0}", "Duplikatsuche fehlgeschlagen: {0}"),

        // ---------- Suche ----------
        ["Find_None"] = ("NO MATCH FOR “{0}”", "KEIN TREFFER FÜR „{0}“"),
        ["Find_One"] = ("ONE MATCH FOR “{0}”", "EIN TREFFER FÜR „{0}“"),
        ["Find_Many"] = ("{0} MATCHES FOR “{1}”, LARGEST FIRST",
                         "{0} TREFFER FÜR „{1}“, GRÖSSTE ZUERST"),

        // ---------- Statuszeile ----------
        ["Stat_Scanning"] = ("Scanning …  {0} entries", "Scan läuft …  {0} Einträge"),
        ["Stat_ScanningShort"] = ("Scanning …", "Scan läuft …"),
        ["Stat_Done"] = ("Scanned in {0} s{1}{2}", "Scan in {0} s{1}{2}"),
        ["Stat_Unreadable"] = ("  ·  {0} folders unreadable", "  ·  {0} Ordner nicht lesbar"),
        ["Stat_Gap"] = ("  ·  {0} {1} Windows reports", "  ·  {0} {1} Windows meldet"),
        ["Stat_More"] = ("more than", "mehr als"),
        ["Stat_Less"] = ("less than", "weniger als"),
        ["Stat_Cancelled"] = ("Scan cancelled", "Scan abgebrochen"),
        ["Stat_ScanFailed"] = ("Scan failed: {0}", "Scan fehlgeschlagen: {0}"),
        ["Stat_NotFound"] = ("Folder not found: {0}", "Verzeichnis nicht gefunden: {0}"),
        ["Stat_Cached"] = ("State of {0}  ·  Browse for a new scan",
                           "Stand von {0}  ·  Durchsuchen für einen neuen Scan"),
        ["Stat_PathCopied"] = ("Path copied", "Pfad kopiert"),
        ["Stat_Exported"] = ("Exported to {0}", "Exportiert nach {0}"),
        ["Stat_ExportFailed"] = ("Export failed: {0}", "Export fehlgeschlagen: {0}"),
        ["Stat_PickFailed"] = ("Selection failed: {0}", "Auswahl fehlgeschlagen: {0}"),
        ["Stat_Failed"] = ("Something went wrong: {0}", "Etwas ist schiefgegangen: {0}"),
        ["Stat_ExplorerFailed"] = ("Explorer would not open: {0}",
                                   "Explorer ließ sich nicht öffnen: {0}"),

        // ---------- Ordnerauswahl ----------
        ["Pick_Title"] = ("Choose a folder or drive", "Ordner oder Laufwerk wählen"),
        ["Pick_Shortcuts"] = ("QUICK ACCESS", "SCHNELLZUGRIFF"),
        ["Pick_Scan"] = ("Scan", "Scannen"),
        ["Pick_Profile"] = ("User folder", "Benutzerordner"),
        ["Pick_Documents"] = ("Documents", "Dokumente"),
        ["Pick_Pictures"] = ("Pictures", "Bilder"),
        ["Pick_Videos"] = ("Videos", "Videos"),
        ["Pick_Downloads"] = ("Downloads", "Downloads"),
        ["Pick_Programs"] = ("Program Files", "Programme"),
        ["Pick_AppData"] = ("App data (local)", "App-Daten (lokal)"),
        ["Pick_NoSubfolders"] = ("No subfolders", "Keine Unterordner"),
        ["Pick_Up"] = ("One level up", "Eine Ebene höher"),
        ["Pick_Denied"] = ("This folder cannot be opened",
                           "Auf diesen Ordner ist kein Zugriff möglich"),

        // ---------- Einstellungen ----------
        ["Set_Title"] = ("Settings", "Einstellungen"),
        ["Set_Language"] = ("LANGUAGE", "SPRACHE"),
        ["Set_LanguageHint"] = ("Applies the next time you start DiskStats",
                                "Wirkt beim nächsten Start von DiskStats"),
        ["Set_Theme"] = ("THEME", "THEMA"),
        ["Set_ThemeSystem"] = ("System", "System"),
        ["Set_ThemeLight"] = ("Light", "Hell"),
        ["Set_ThemeDark"] = ("Dark", "Dunkel"),
        ["Set_Appearance"] = ("APPEARANCE", "DARSTELLUNG"),
        ["Set_Motion"] = ("Motion", "Bewegung"),
        ["Set_MotionHint"] = ("Shapes grow in instead of appearing",
                              "Flächen wachsen herein, statt zu erscheinen"),
        ["Set_Detail"] = ("Map detail", "Detailgrad der Karte"),
        ["Set_DetailHint"] = ("How small a file may be and still get its own area",
                              "Wie klein eine Datei noch eine eigene Fläche bekommt"),
        ["Set_DetailCoarse"] = ("Coarse", "Grob"),
        ["Set_DetailNormal"] = ("Normal", "Normal"),
        ["Set_DetailFine"] = ("Fine", "Fein"),
        ["Set_Scan"] = ("SCAN", "SCAN"),
        ["Set_AutoWorkers"] = ("Choose parallel readers automatically",
                               "Parallele Zugriffe automatisch wählen"),
        ["Set_AutoWorkersHint"] = ("Core count on flash storage, throttled on spinning disks",
                                   "Kernzahl auf Flash-Speicher, gedrosselt auf drehenden Platten"),
        ["Set_Sizes"] = ("SIZE UNITS", "GRÖSSENANGABEN"),
        ["Set_SizesBinary"] = ("Binary", "Binär"),
        ["Set_SizesDecimal"] = ("Decimal", "Dezimal"),
        ["Set_SizesBinaryHint"] = ("1 GB = 1024 MB. The way Explorer counts.",
                                   "1 GB = 1024 MB. So rechnet der Explorer."),
        ["Set_SizesDecimalHint"] = ("1 GB = 1000 MB. The way manufacturers advertise.",
                                    "1 GB = 1000 MB. So werben Hersteller."),
        ["Set_Immediate"] = ("Changes take effect at once", "Änderungen wirken sofort"),
        ["Set_Privacy"] = ("Privacy policy", "Datenschutzerklärung"),
        ["Set_Support"] = ("Support: kroxoko@gmail.com", "Support: kroxoko@gmail.com"),
        ["Set_License"] = ("Open source · MIT License · © 2026 RINGPAPERS",
                             "Open Source · MIT-Lizenz · © 2026 RINGPAPERS"),

        // ---------- CSV ----------
        ["Csv_Path"] = ("Path", "Pfad"),
        ["Csv_Name"] = ("Name", "Name"),
        ["Csv_Type"] = ("Type", "Typ"),
        ["Csv_Bytes"] = ("Size in bytes", "Größe in Bytes"),
        ["Csv_Modified"] = ("Modified", "Geändert"),
        ["Csv_Folder"] = ("Folder", "Ordner"),
        ["Csv_File"] = ("File", "Datei"),
        ["Csv_Failed"] = ("CSV export failed", "CSV-Export fehlgeschlagen"),

        // ---------- Ansichten, Zeichenflaeche ----------
        // Datumsformat fuer Monat und Jahr in der Altersliste.
        ["View_MonthYear"] = ("MM/yyyy", "MM.yyyy"),
    };
}
